name: First workflow

on : [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Greeting
        run: echo "Hello! From ${{ github.workflow }} triggered by ${{ github.event_name }} by ${{ github.actor }}"  

      - uses: actions/setup-dotnet@v1.5
        with:
          dotnet-version: '3.1.x'
      - name: Build & Test
        run: |
          dotnet build
          dotnet test test\Example.UnitTests\Example.UnitTests.csproj
          
