name: First workflow

on : [push]

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOs-latest]

    name: ${{ matrix.os }}
    
    steps:

      - uses: actions/checkout@v2

      - name: Greeting
        run: echo "Hello! From ${{ github.workflow }} triggered by ${{ github.event_name }} by ${{ github.actor }}"  

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Build & Test
        run: |
          dotnet build
          dotnet test
          
